/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/j5Ca3uBNltP
 */


export function Banner() {
  return (
    <div className="relative w-full h-12">
      <div className="absolute inset-0 flex items-center">
        <div className="w-full h-2 bg-green-500 to-green-500 opacity-90" />
        <div className="w-full h-2 bg-green-500 to-fuchsia-500 opacity-90 animation-ping" />
      </div>
      <div className="container flex items-center justify-center px-4 md:px-6">
        <p className="text-sm font-semibold tracking-wide text-black-900 dark:text-black-100">
          Site em construção 😉 em breve um novo design 💪
        </p>
      </div>
    </div>
  )
}
